// Generated from: features\comprar.feature
import { test } from "playwright-bdd";

test.describe('Comprar un producto', () => {

  test.beforeEach('Background', async ({ Given, page }, testInfo) => { if (testInfo.error) return;
    await Given('que el usuario navega a la página de inicio', null, { page }); 
  });
  
  test.describe('El usuario puede agregar un producto al carrito desde la página de productos', () => {

    test('Example #1', async ({ Given, When, And, page }) => { 
      await Given('ingresa el usuario "standard_user" y la contraseña "secret_sauce"', null, { page }); 
      await And('que el usuario agrega el producto "Sauce Labs Backpack" al carrito', null, { page }); 
      await When('el contador del carrito debe mostrar "1" unidad', null, { page }); 
    });

  });

  test.describe('El usuario puede ver los productos agregados en el carrito de compras.', () => {

    test('Example #1', async ({ Given, When, Then, And, page }) => { 
      await Given('ingresa el usuario "standard_user" y la contraseña "secret_sauce"', null, { page }); 
      await And('que el usuario agrega el producto "Sauce Labs Backpack" al carrito', null, { page }); 
      await When('debería ser redirigido al "cart.html" de "Your Cart" del carrito', null, { page }); 
      await Then('el producto "Sauce Labs Backpack" debe estar visible en el carrito', null, { page }); 
    });

    test('Example #2', async ({ Given, When, Then, And, page }) => { 
      await Given('ingresa el usuario "standard_user" y la contraseña "secret_sauce"', null, { page }); 
      await And('que el usuario agrega el producto "Sauce Labs Bike Light" al carrito', null, { page }); 
      await When('debería ser redirigido al "cart.html" de "Your Cart" del carrito', null, { page }); 
      await Then('el producto "Sauce Labs Bike Light" debe estar visible en el carrito', null, { page }); 
    });

    test('Example #3', async ({ Given, When, Then, And, page }) => { 
      await Given('ingresa el usuario "standard_user" y la contraseña "secret_sauce"', null, { page }); 
      await And('que el usuario agrega el producto "Sauce Labs Bolt T-Shirt" al carrito', null, { page }); 
      await When('debería ser redirigido al "cart.html" de "Your Cart" del carrito', null, { page }); 
      await Then('el producto "Sauce Labs Bolt T-Shirt" debe estar visible en el carrito', null, { page }); 
    });

    test('Example #4', async ({ Given, When, Then, And, page }) => { 
      await Given('ingresa el usuario "standard_user" y la contraseña "secret_sauce"', null, { page }); 
      await And('que el usuario agrega el producto "Sauce Labs Fleece Jacket" al carrito', null, { page }); 
      await When('debería ser redirigido al "cart.html" de "Your Cart" del carrito', null, { page }); 
      await Then('el producto "Sauce Labs Fleece Jacket" debe estar visible en el carrito', null, { page }); 
    });

    test('Example #5', async ({ Given, When, Then, And, page }) => { 
      await Given('ingresa el usuario "standard_user" y la contraseña "secret_sauce"', null, { page }); 
      await And('que el usuario agrega el producto "Sauce Labs Onesie" al carrito', null, { page }); 
      await When('debería ser redirigido al "cart.html" de "Your Cart" del carrito', null, { page }); 
      await Then('el producto "Sauce Labs Onesie" debe estar visible en el carrito', null, { page }); 
    });

    test('Example #6', async ({ Given, When, Then, And, page }) => { 
      await Given('ingresa el usuario "standard_user" y la contraseña "secret_sauce"', null, { page }); 
      await And('que el usuario agrega el producto "Test.allTheThings() T-Shirt (Red)" al carrito', null, { page }); 
      await When('debería ser redirigido al "cart.html" de "Your Cart" del carrito', null, { page }); 
      await Then('el producto "Test.allTheThings() T-Shirt (Red)" debe estar visible en el carrito', null, { page }); 
    });

  });

  test.describe('El usuario puede completar el proceso de compra hasta la confirmación.', () => {

    test('Example #1', async ({ Given, When, Then, And, page }) => { 
      await Given('ingresa el usuario "standard_user" y la contraseña "secret_sauce"', null, { page }); 
      await And('que el usuario agrega el producto "Sauce Labs Backpack" al carrito', null, { page }); 
      await When('debería ser redirigido al "cart.html" de "Your Cart" del carrito', null, { page }); 
      await When('se encuentra en la pantalla de checkout de informacion del cliente', null, { page }); 
      await And('completa el formulario el nombre "Juan" , apellido "Perez" y codigo postal "12345"', null, { page }); 
      await Then('deber ver un mensaje de confirmación "Thank you for your order!"', null, { page }); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features\\comprar.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":11,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given que el usuario navega a la página de inicio","isBg":true,"stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given ingresa el usuario \"standard_user\" y la contraseña \"secret_sauce\"","stepMatchArguments":[{"group":{"start":19,"value":"\"standard_user\"","children":[{"start":20,"value":"standard_user","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"secret_sauce\"","children":[{"start":52,"value":"secret_sauce","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And que el usuario agrega el producto \"Sauce Labs Backpack\" al carrito","stepMatchArguments":[{"group":{"start":34,"value":"\"Sauce Labs Backpack\"","children":[{"start":35,"value":"Sauce Labs Backpack","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":15,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When el contador del carrito debe mostrar \"1\" unidad","stepMatchArguments":[{"group":{"start":37,"value":"\"1\"","children":[{"start":38,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":22,"pickleLine":20,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given que el usuario navega a la página de inicio","isBg":true,"stepMatchArguments":[]},{"pwStepLine":23,"gherkinStepLine":14,"keywordType":"Context","textWithKeyword":"Given ingresa el usuario \"standard_user\" y la contraseña \"secret_sauce\"","stepMatchArguments":[{"group":{"start":19,"value":"\"standard_user\"","children":[{"start":20,"value":"standard_user","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"secret_sauce\"","children":[{"start":52,"value":"secret_sauce","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":24,"gherkinStepLine":15,"keywordType":"Context","textWithKeyword":"And que el usuario agrega el producto \"Sauce Labs Backpack\" al carrito","stepMatchArguments":[{"group":{"start":34,"value":"\"Sauce Labs Backpack\"","children":[{"start":35,"value":"Sauce Labs Backpack","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":25,"gherkinStepLine":16,"keywordType":"Action","textWithKeyword":"When debería ser redirigido al \"cart.html\" de \"Your Cart\" del carrito","stepMatchArguments":[{"group":{"start":26,"value":"\"cart.html\"","children":[{"start":27,"value":"cart.html","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Your Cart\"","children":[{"start":42,"value":"Your Cart","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":26,"gherkinStepLine":17,"keywordType":"Outcome","textWithKeyword":"Then el producto \"Sauce Labs Backpack\" debe estar visible en el carrito","stepMatchArguments":[{"group":{"start":12,"value":"\"Sauce Labs Backpack\"","children":[{"start":13,"value":"Sauce Labs Backpack","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":29,"pickleLine":21,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given que el usuario navega a la página de inicio","isBg":true,"stepMatchArguments":[]},{"pwStepLine":30,"gherkinStepLine":14,"keywordType":"Context","textWithKeyword":"Given ingresa el usuario \"standard_user\" y la contraseña \"secret_sauce\"","stepMatchArguments":[{"group":{"start":19,"value":"\"standard_user\"","children":[{"start":20,"value":"standard_user","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"secret_sauce\"","children":[{"start":52,"value":"secret_sauce","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":31,"gherkinStepLine":15,"keywordType":"Context","textWithKeyword":"And que el usuario agrega el producto \"Sauce Labs Bike Light\" al carrito","stepMatchArguments":[{"group":{"start":34,"value":"\"Sauce Labs Bike Light\"","children":[{"start":35,"value":"Sauce Labs Bike Light","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":32,"gherkinStepLine":16,"keywordType":"Action","textWithKeyword":"When debería ser redirigido al \"cart.html\" de \"Your Cart\" del carrito","stepMatchArguments":[{"group":{"start":26,"value":"\"cart.html\"","children":[{"start":27,"value":"cart.html","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Your Cart\"","children":[{"start":42,"value":"Your Cart","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":17,"keywordType":"Outcome","textWithKeyword":"Then el producto \"Sauce Labs Bike Light\" debe estar visible en el carrito","stepMatchArguments":[{"group":{"start":12,"value":"\"Sauce Labs Bike Light\"","children":[{"start":13,"value":"Sauce Labs Bike Light","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":36,"pickleLine":22,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given que el usuario navega a la página de inicio","isBg":true,"stepMatchArguments":[]},{"pwStepLine":37,"gherkinStepLine":14,"keywordType":"Context","textWithKeyword":"Given ingresa el usuario \"standard_user\" y la contraseña \"secret_sauce\"","stepMatchArguments":[{"group":{"start":19,"value":"\"standard_user\"","children":[{"start":20,"value":"standard_user","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"secret_sauce\"","children":[{"start":52,"value":"secret_sauce","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":15,"keywordType":"Context","textWithKeyword":"And que el usuario agrega el producto \"Sauce Labs Bolt T-Shirt\" al carrito","stepMatchArguments":[{"group":{"start":34,"value":"\"Sauce Labs Bolt T-Shirt\"","children":[{"start":35,"value":"Sauce Labs Bolt T-Shirt","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":16,"keywordType":"Action","textWithKeyword":"When debería ser redirigido al \"cart.html\" de \"Your Cart\" del carrito","stepMatchArguments":[{"group":{"start":26,"value":"\"cart.html\"","children":[{"start":27,"value":"cart.html","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Your Cart\"","children":[{"start":42,"value":"Your Cart","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":40,"gherkinStepLine":17,"keywordType":"Outcome","textWithKeyword":"Then el producto \"Sauce Labs Bolt T-Shirt\" debe estar visible en el carrito","stepMatchArguments":[{"group":{"start":12,"value":"\"Sauce Labs Bolt T-Shirt\"","children":[{"start":13,"value":"Sauce Labs Bolt T-Shirt","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":43,"pickleLine":23,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given que el usuario navega a la página de inicio","isBg":true,"stepMatchArguments":[]},{"pwStepLine":44,"gherkinStepLine":14,"keywordType":"Context","textWithKeyword":"Given ingresa el usuario \"standard_user\" y la contraseña \"secret_sauce\"","stepMatchArguments":[{"group":{"start":19,"value":"\"standard_user\"","children":[{"start":20,"value":"standard_user","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"secret_sauce\"","children":[{"start":52,"value":"secret_sauce","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":15,"keywordType":"Context","textWithKeyword":"And que el usuario agrega el producto \"Sauce Labs Fleece Jacket\" al carrito","stepMatchArguments":[{"group":{"start":34,"value":"\"Sauce Labs Fleece Jacket\"","children":[{"start":35,"value":"Sauce Labs Fleece Jacket","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":46,"gherkinStepLine":16,"keywordType":"Action","textWithKeyword":"When debería ser redirigido al \"cart.html\" de \"Your Cart\" del carrito","stepMatchArguments":[{"group":{"start":26,"value":"\"cart.html\"","children":[{"start":27,"value":"cart.html","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Your Cart\"","children":[{"start":42,"value":"Your Cart","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":47,"gherkinStepLine":17,"keywordType":"Outcome","textWithKeyword":"Then el producto \"Sauce Labs Fleece Jacket\" debe estar visible en el carrito","stepMatchArguments":[{"group":{"start":12,"value":"\"Sauce Labs Fleece Jacket\"","children":[{"start":13,"value":"Sauce Labs Fleece Jacket","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":50,"pickleLine":24,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given que el usuario navega a la página de inicio","isBg":true,"stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":14,"keywordType":"Context","textWithKeyword":"Given ingresa el usuario \"standard_user\" y la contraseña \"secret_sauce\"","stepMatchArguments":[{"group":{"start":19,"value":"\"standard_user\"","children":[{"start":20,"value":"standard_user","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"secret_sauce\"","children":[{"start":52,"value":"secret_sauce","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":52,"gherkinStepLine":15,"keywordType":"Context","textWithKeyword":"And que el usuario agrega el producto \"Sauce Labs Onesie\" al carrito","stepMatchArguments":[{"group":{"start":34,"value":"\"Sauce Labs Onesie\"","children":[{"start":35,"value":"Sauce Labs Onesie","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":53,"gherkinStepLine":16,"keywordType":"Action","textWithKeyword":"When debería ser redirigido al \"cart.html\" de \"Your Cart\" del carrito","stepMatchArguments":[{"group":{"start":26,"value":"\"cart.html\"","children":[{"start":27,"value":"cart.html","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Your Cart\"","children":[{"start":42,"value":"Your Cart","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":54,"gherkinStepLine":17,"keywordType":"Outcome","textWithKeyword":"Then el producto \"Sauce Labs Onesie\" debe estar visible en el carrito","stepMatchArguments":[{"group":{"start":12,"value":"\"Sauce Labs Onesie\"","children":[{"start":13,"value":"Sauce Labs Onesie","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":57,"pickleLine":25,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given que el usuario navega a la página de inicio","isBg":true,"stepMatchArguments":[]},{"pwStepLine":58,"gherkinStepLine":14,"keywordType":"Context","textWithKeyword":"Given ingresa el usuario \"standard_user\" y la contraseña \"secret_sauce\"","stepMatchArguments":[{"group":{"start":19,"value":"\"standard_user\"","children":[{"start":20,"value":"standard_user","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"secret_sauce\"","children":[{"start":52,"value":"secret_sauce","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":59,"gherkinStepLine":15,"keywordType":"Context","textWithKeyword":"And que el usuario agrega el producto \"Test.allTheThings() T-Shirt (Red)\" al carrito","stepMatchArguments":[{"group":{"start":34,"value":"\"Test.allTheThings() T-Shirt (Red)\"","children":[{"start":35,"value":"Test.allTheThings() T-Shirt (Red)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":60,"gherkinStepLine":16,"keywordType":"Action","textWithKeyword":"When debería ser redirigido al \"cart.html\" de \"Your Cart\" del carrito","stepMatchArguments":[{"group":{"start":26,"value":"\"cart.html\"","children":[{"start":27,"value":"cart.html","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Your Cart\"","children":[{"start":42,"value":"Your Cart","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":17,"keywordType":"Outcome","textWithKeyword":"Then el producto \"Test.allTheThings() T-Shirt (Red)\" debe estar visible en el carrito","stepMatchArguments":[{"group":{"start":12,"value":"\"Test.allTheThings() T-Shirt (Red)\"","children":[{"start":13,"value":"Test.allTheThings() T-Shirt (Red)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":68,"pickleLine":36,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given que el usuario navega a la página de inicio","isBg":true,"stepMatchArguments":[]},{"pwStepLine":69,"gherkinStepLine":28,"keywordType":"Context","textWithKeyword":"Given ingresa el usuario \"standard_user\" y la contraseña \"secret_sauce\"","stepMatchArguments":[{"group":{"start":19,"value":"\"standard_user\"","children":[{"start":20,"value":"standard_user","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"secret_sauce\"","children":[{"start":52,"value":"secret_sauce","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":70,"gherkinStepLine":29,"keywordType":"Context","textWithKeyword":"And que el usuario agrega el producto \"Sauce Labs Backpack\" al carrito","stepMatchArguments":[{"group":{"start":34,"value":"\"Sauce Labs Backpack\"","children":[{"start":35,"value":"Sauce Labs Backpack","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":71,"gherkinStepLine":30,"keywordType":"Action","textWithKeyword":"When debería ser redirigido al \"cart.html\" de \"Your Cart\" del carrito","stepMatchArguments":[{"group":{"start":26,"value":"\"cart.html\"","children":[{"start":27,"value":"cart.html","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Your Cart\"","children":[{"start":42,"value":"Your Cart","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":72,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"When se encuentra en la pantalla de checkout de informacion del cliente","stepMatchArguments":[]},{"pwStepLine":73,"gherkinStepLine":32,"keywordType":"Action","textWithKeyword":"And completa el formulario el nombre \"Juan\" , apellido \"Perez\" y codigo postal \"12345\"","stepMatchArguments":[{"group":{"start":33,"value":"\"Juan\"","children":[{"start":34,"value":"Juan","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"Perez\"","children":[{"start":52,"value":"Perez","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":75,"value":"\"12345\"","children":[{"start":76,"value":"12345","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":74,"gherkinStepLine":33,"keywordType":"Outcome","textWithKeyword":"Then deber ver un mensaje de confirmación \"Thank you for your order!\"","stepMatchArguments":[{"group":{"start":37,"value":"\"Thank you for your order!\"","children":[{"start":38,"value":"Thank you for your order!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end